In [1]:
import numpy as np
from numpy.linalg import inv
a = np.array([[3., 2., -1.], [2., -2., 4.], [-1., 0.5, -1.]])

In [2]:
print(a)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]


In [3]:
ainv = inv(a)
print (ainv)

[[ 1.48029737e-16 -5.00000000e-01 -2.00000000e+00]
 [ 6.66666667e-01  1.33333333e+00  4.66666667e+00]
 [ 3.33333333e-01  1.16666667e+00  3.33333333e+00]]


In [4]:
b = np.array([1,-2,0])

In [5]:
X = np.dot(ainv,b)
print ('ainv*b=', X)

ainv*b= [ 1. -2. -2.]


In [6]:
asolve = np.linalg.solve(a,b)
print('asolve*b=', asolve)

asolve*b= [ 1. -2. -2.]
